"""add custom columns to user

Revision ID: a160ece5f5a0
Revises: ffdc0a98111c
Create Date: 2022-05-10 17:20:57.546363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a160ece5f5a0'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('remaining_fetches', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_fetch', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('init_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('users', sa.Column('cash_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('users', sa.Column('assets_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('users', sa.Column('value_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'value_history')
    op.drop_column('users', 'assets_value')
    op.drop_column('users', 'cash_value')
    op.drop_column('users', 'init_value')
    op.drop_column('users', 'last_fetch')
    op.drop_column('users', 'remaining_fetches')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
