"""fixed one column remaining fetxhes

Revision ID: 2d6b5b81d0f8
Revises: a160ece5f5a0
Create Date: 2022-05-10 17:23:32.154867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6b5b81d0f8'
down_revision = 'a160ece5f5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'remaining_fetches',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'remaining_fetches',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
